SET SCHEMA TRIVAGOSEARCH;

INSERT INTO USER (USERNAME, PASSWORD, BONUS_POINTS) VALUES ('user1', '$2y$12$02rjVmshqUbym8OR8NePfOKKyrl200Y09Qgy8m7N6LtrO8dNTgtBW', 100);
INSERT INTO USER (USERNAME, PASSWORD, BONUS_POINTS) VALUES ('user2', '$2y$12$EMeRn.bC.9wXoqe.8Cl9Ouytx0uPMVpcTFLQzhKR36ZeHpRDOJYx6', 50);
INSERT INTO USER (USERNAME, PASSWORD, BONUS_POINTS) VALUES ('user3', '$2y$12$swn9kqdxXVDfb9/U4Q3l1uzV92DZuX2TzZ5xKR.JnXc9BN085jPk.', 45);

INSERT INTO ROLE (DESCRIPTION, NAME) VALUES ('ADMIN ROLE', 'ADMIN');
INSERT INTO ROLE (DESCRIPTION, NAME) VALUES ('USER ROLE', 'USER');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 2);