SET SCHEMA HOTELSEARCH;

INSERT INTO USER (USERNAME, PASSWORD, BONUS_POINTS) VALUES ('user1', '$2a$04$.65Dq64AEHFUcbp/6lrMbeusSJ0ojEr0Tv42R2nL/gdBddeObXvmm', 100);
INSERT INTO USER (USERNAME, PASSWORD, BONUS_POINTS) VALUES ('user2', '$2a$04$.65Dq64AEHFUcbp/6lrMbeusSJ0ojEr0Tv42R2nL/gdBddeObXvmm', 50);
INSERT INTO USER (USERNAME, PASSWORD, BONUS_POINTS) VALUES ('user3', '$2a$04$Lk4zqXHrHd82w5/tiMy8ru9RpAXhvFfmHOuqTmFPWQcUhBD8SSJ6W', 45);

INSERT INTO ROLE (DESCRIPTION, NAME) VALUES ('ADMIN ROLE', 'ADMIN');
INSERT INTO ROLE (DESCRIPTION, NAME) VALUES ('USER ROLE', 'USER');
COMMIT;



INSERT INTO HOTEL(NAME, ROOM_TYPE, BOOKING_AMOUNT, BONUS_POINTS) 
VALUES ('Grand Legacy', 'DELUX', 20, 60);
INSERT INTO HOTEL(NAME, ROOM_TYPE, BOOKING_AMOUNT, BONUS_POINTS) 
VALUES ('Grand Legacy', 'EXECUTIVE', 30, 80);
INSERT INTO HOTEL(NAME, ROOM_TYPE, BOOKING_AMOUNT, BONUS_POINTS) 
VALUES ('Grand Hotel', 'DELUX', 10, 30);
INSERT INTO HOTEL(NAME, ROOM_TYPE, BOOKING_AMOUNT, BONUS_POINTS) 
VALUES ('Grand Hotel', 'EXECUTIVE', 20, 50);
COMMIT;


INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 2);
COMMIT;


INSERT INTO USER_HOTEL(USER_ID, HOTEL_ID, STATUS) VALUES (1, 1, 'RESERVED');
INSERT INTO USER_HOTEL(USER_ID, HOTEL_ID, STATUS) VALUES (2, 2, 'PENDING APPROVAL');
COMMIT;
