    DROP SCHEMA IF EXISTS HOTELSEARCH;
    COMMIT;
    
    CREATE SCHEMA HOTELSEARCH;
    SET SCHEMA HOTELSEARCH;
    
    DROP TABLE IF EXISTS ROLE;  
    CREATE TABLE ROLE (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(255), 
        DESCRIPTION VARCHAR(255), 
        PRIMARY KEY (ID)
    );

    DROP TABLE IF EXISTS USER;    
    CREATE TABLE USER (
        ID BIGINT NOT NULL AUTO_INCREMENT, 
        USERNAME VARCHAR(255),
        PASSWORD VARCHAR(255),
		BONUS_POINTS BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (ID)
    );
    
    DROP TABLE IF EXISTS USER_ROLES;
    CREATE TABLE USER_ROLES (
        ID BIGINT NOT NULL AUTO_INCREMENT, 
        USER_ID BIGINT NOT NULL, 
        ROLE_ID BIGINT NOT NULL, 
        PRIMARY KEY (ID, USER_ID, ROLE_ID)
    );
    
    DROP TABLE IF EXISTS HOTEL;
    CREATE TABLE HOTEL (
        ID int NOT NULL AUTO_INCREMENT,
        NAME varchar(255) NOT NULL,
        ROOM_TYPE varchar(255) NOT NULL,        
        BOOKING_AMOUNT BIGINT NOT NULL,
        BONUS_POINTS BIGINT NOT NULL,
        PRIMARY KEY (ID, NAME, ROOM_TYPE)
    );
    
    DROP TABLE IF EXISTS USER_HOTEL;
    CREATE TABLE USER_HOTEL (
        ID int NOT NULL AUTO_INCREMENT,
        USER_ID INT NOT NULL,
        HOTEL_ID INT NOT NULL,
        STATUS varchar(30) NOT NULL,
        PRIMARY KEY (ID)        
    );
    
    ALTER TABLE USER_ROLES ADD CONSTRAINT FKRHFOVTCIQ1L558CW6UDG0H0D3 FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);
    ALTER TABLE USER_ROLES ADD CONSTRAINT FK55ITPPKW3I07DO3H7QOCLQD4K FOREIGN KEY (USER_ID) REFERENCES USER (ID);
    ALTER TABLE USER_HOTEL ADD CONSTRAINT user_id_foreign_constraint FOREIGN KEY (USER_ID) REFERENCES USER (ID);
    ALTER TABLE USER_HOTEL ADD CONSTRAINT hotel_id_foreign_constraint FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL (ID);
